create table Menus (

    menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name VARCHAR2 (50) NOT NULL,
    description VARCHAR2(200)
);

CREATE TABLE MenuItems (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id NUMBER NOT NULL,
    item_name VARCHAR2(100) NOT NULL, 
    category VARCHAR2(50) NOT NULL,
    price NUMBER (6,2) NOT NULL, 
    is_available NUMBER(1) DEFAULT 1 NOT NULL, 
    CONSTRAINT fk_menuitems_menu FOREIGN KEY (menu_id) REFERENCES Menus(menu_id), 
    CONSTRAINT chk_price CHECK (price > 0),
    CONSTRAINT chk_available CHECK (is_available IN (0,1))

);


create table Orders (

order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
table_number NUMBER(3) NOT NULL, 
order_status VARCHAR2 (20) DEFAULT 'Pending' NOT NULL, 
CONSTRAINT chk_status CHECK (order_status IN ('Pending', 'In Progress', 'Complete', 'Cancelled'))
);

create table OrderItems (

order_id NUMBER Not null, 
item_id NUMBER NOT NULL, 
quantity NUMBER(3) NOT NULL,
item_price NUMBER(6,2) NOT NULL, 
CONSTRAINT pk_orderitems PRIMARY KEY (order_id, item_id), 
CONSTRAINT fk_orderitems_orders FOREIGN KEY (order_id) REFERENCES Orders(order_id),
CONSTRAINT fk_orderitems_menuitems FOREIGN KEY (item_id) REFERENCES MenuItems(item_id),
CONSTRAINT chk_quantity CHECK (quantity > 0) 

);

-- option 1, inserting one at a time 
insert into Menus (menu_id, menu_name, description)
Values (1, 'Main Dining' , 'Standard dinner menu items');

insert into Menus (menu_id, menu_name, description)
Values (2, 'Beverages', 'Soft Drinks, wine and spirits');

-- option 2, inserting in bulk using the insert all option 
INSERT ALL 
into MenuItems(item_id, menu_id, item_name, category, price, is_available) Values (10, 1, 'Truffle Burger', 'Entree', 18.50, 1)
into MenuItems(item_id, menu_id, item_name, category, price, is_available) Values (11, 1, 'Ribeye Steak', 'Entree', 34.00, 1)
into MenuItems(item_id, menu_id, item_name, category, price, is_available) Values (12, 1, 'Wild Mushroom Pasta', 'Entree', 22.00, 0)
into MenuItems(item_id, menu_id, item_name, category, price, is_available) Values (13, 2, 'Craft Soda', 'Beverage', 4.50, 1)
into MenuItems(item_id, menu_id, item_name, category, price, is_available) Values (14, 2, 'House Red Wine', 'Beverage', 12.00, 1)

Select * From dual; 

INSERT ALL 
INTO Orders (order_id, table_number, order_status) VALUES (101, 4, 'Complete')
INTO Orders (order_id, table_number, order_status) VALUES (102, 2, 'Complete')
INTO Orders (order_id, table_number, order_status) VALUES (103, 7, 'In Progress')

SELECT * FROM dual; 

INSERT ALL 
INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (101, 10, 2, 18.50) 
INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (101, 13, 2, 4.50)
INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (102, 11, 1, 34.00) 
INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (102, 14, 1, 28.00) 
INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (103, 10, 1, 18.50)
INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (103, 13, 1, 4.50)
INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (103, 14, 2, 12.50)

Select * FROM dual; 

COMMIT; -- commit saves changes intto the data base 

-- finding everything that is an exact match with = 

Select 
item_id, 
item_name,
price 
from MenuItems
Where Category = 'Entree'; 


-- finding everything that does NOT match

Select 
order_id, 
table_number,
order_status
FROM Orders
Where order_status != 'Complete';




-- filtering numerical values 
SELECT 
item_name, 
price
FROM MenuItems
WHERE price > 15.00; 

-- the and operator allows us to combine multiple WHERE clauses (all have to be true) 

SELECT  
item_name, 
category, 
price
FROM MenuItems
WHERE category = 'Beverage' AND price < 10.00; 


-- the or operator does the same, but only one has to be true 
SELECT
item_name, 
category, 
price
FROM MenuItems
WHERE category = 'Beverage' OR price > 30.00; 


-- IN lets us group multiple things together for the same category without using an OR 
SELECT 
order_id,
table_number,
order_status
FROM Orders
WHERE order_status IN ('Pending', 'In Progress'); -- WHERE order_status = 'Pending' OR  WHERE order_status = 'In Progress'

-- the between operator allows us to specify a range of values we want to be within 
SELECT 
item_name, 
price
FROM MenuItems
WHERE price BETWEEN 10.00 AND 25.00; 

-- like operator % allows us to search for similar items 
SELECT 
item_id, 
item_name
FROM MenuItems
WHERE item_name LIKE '%Burger%';

-- null checks allow us to look for missing data
SELECT
menu_id,
menu_name, 
description 
FROM Menus
WHERE description is null; 


-- a standard join(inner join) allows us to get records from two tables where keys match 
SELECT 
m.item_name, 
m.category, 
mn.menu_name
FROM MenuItems m 
JOIN Menus mn ON m.menu_id = mn.menu_id; 


-- a left join brings all records from the left table, PLUS the matching records from the right 

SELECT 
m.item_name, 
oi.order_id, 
oi.quantity
FROM MenuItems m
LEFT JOIN OrderItems oi ON m.item_id = oi.item_id; 

-- group by allows us to combine multiple matching values into a summary row 

SELECT category, 
COUNT(*) AS total_items
FROM MenuItems
GROUP BY category; 


-- the HAVING clause can be combined with the groupby clause to perform calculations on the summary rows 

SELECT 
category, 
AVG(price) AS average_price
FROM 
MenuItems
Group BY category 
HAVING AVG(price) > 10.00; 







-- INNER JOIN -- standard join operator 
-- the inner join is the default join. it only includes the that have matching information. --
-- in both tables related to the join. --
-- if table A (menuItems doesn't have a matching item in table B(orderItems), 
-- That record is not included 
-- INNER joins are used to show data where a STRICT LINK between the tables 



SELECT 
m.item_id, 
m.item_name, 
oi.order_id, 
oi.quantity
FROM MenuItems m 
INNER JOIN OrderItems oi ON m.item_id = oi.item_id; 

-- LEFT JOIN /LEFT OUTER JOIN --
-- returns ALL rows from the table on the LEFT, alongside the matching records from the right 
-- if a row in the LEFT table has no corresponding records in the right table 
-- The row is still displayed, however any columns from the right table will have a null sintead of a value

SELECT   
m.item_id, 
m.item_name ,
oi.order_id,
oi.quantity
FROM MenuItems m 
LEFT JOIN OrderItems oi ON m.item_id = oi.item_id; 



-- right join / RIGHT OUTER join  
SELECT   
m.item_id, 
m.item_name ,
oi.order_id,
oi.quantity
FROM MenuItems m 
RIGHT JOIN OrderItems oi ON m.item_id = oi.item_id; 




-- full JOIN / full OUTER JOIN 
-- it combines the inner , left and right join into one BIG FULL JOIN 
-- it brings all of the rows, from the left and right tables and where they have an interaction 
-- values are shown form both tables
-- however, any information that does not have a corresponding data in the other table is show anyways 


SELECT   
m.item_id, 
m.item_name ,
oi.order_id,
oi.quantity
FROM MenuItems m 
FULL OUTER JOIN OrderItems oi ON m.item_id = oi.item_id; 





 













