CREATE TABLE Menus (
    menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name VARCHAR2(50) NOT NULL,
    description VARCHAR2(200)
);

CREATE TABLE MenuItems (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id NUMBER NOT NULL,
    item_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    price NUMBER(6,2) NOT NULL,
    is_available NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_menuitems_menu FOREIGN KEY (menu_id) REFERENCES Menus(menu_id),
    CONSTRAINT chk_price CHECK (price > 0),
    CONSTRAINT chk_available CHECK (is_available IN (0,1))
);

CREATE TABLE Orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    table_number NUMBER(3) NOT NULL,
    order_status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
    CONSTRAINT chk_status CHECK (order_status IN ('Pending', 'In Progress', 'Completed', 'Cancelled'))
);

CREATE TABLE OrderItems (
    order_id NUMBER NOT NULL,
    item_id NUMBER NOT NULL,
    quantity NUMBER(3) NOT NULL,
    item_price NUMBER(6, 2) NOT NULL,
    CONSTRAINT pk_orderitems PRIMARY KEY (order_id, item_id),
    CONSTRAINT fk_orderitems_orders FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    CONSTRAINT fk_orderitems_menuitems FOREIGN KEY (item_id) REFERENCES MenuItems(item_id),
    CONSTRAINT chk_quantity CHECK (quantity > 0)
);

INSERT INTO Menus (menu_id, menu_name, description)
VALUES (1, 'Main Dining', 'Standard dinner menu items');

INSERT INTO Menus (menu_id, menu_name, description)
VALUES (2, 'Beverages', 'Soft drinks, wine, and spirits');

INSERT ALL 
    INTO MenuItems (item_id, menu_id, item_name, category, price, is_available) VALUES (10, 1, 'Truffle Burger', 'Entree', 18.50, 1)
    INTO MenuItems (item_id, menu_id, item_name, category, price, is_available) VALUES (11, 1, 'Ribeye Steak', 'Entree', 34.00, 1)
    INTO MenuItems (item_id, menu_id, item_name, category, price, is_available) VALUES (12, 1, 'Wild Mushroom', 'Entree', 22.00, 0)
    INTO MenuItems (item_id, menu_id, item_name, category, price, is_available) VALUES (13, 2, 'Craft Beer', 'Beverage', 4.50, 1)
    INTO MenuItems (item_id, menu_id, item_name, category, price, is_available) VALUES (14, 2, 'House Red Wine', 'Beverage', 12.00, 1)
SELECT * FROM dual;

INSERT ALL 
    INTO Orders (order_id, table_number, order_status) VALUES (101, 4, 'Completed')
    INTO Orders (order_id, table_number, order_status) VALUES (102, 2, 'Completed')
    INTO Orders (order_id, table_number, order_status) VALUES (103, 7, 'In Progress')
SELECT * FROM dual;

INSERT ALL
    INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (101, 10, 2, 18.50)
    INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (101, 13, 2, 4.50)
    INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (102, 11, 1, 34.00)
    INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (102, 14, 1, 28.00)
    INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (103, 10, 1, 18.50)
    INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (103, 13, 1, 4.50)
    INTO OrderItems (order_id, item_id, quantity, item_price) VALUES (103, 14, 1, 12.00)
SELECT * FROM dual;

Commit;

SELECT item_id, item_name, price 
FROM MenuItems
WHERE category = 'Entree';

SELECT order_id, table_number, order_status
FROM Orders
WHERE order_status != 'Completed';